### ISSUE TITLE
Alternative replace method

### ISSUE THREAD

**Issue by jareis** [hr-it-solutions/DD_J_plg_system_disable-bootstrap#17]
Hello,
Your solution didn't work in Joomla! 3.6.2, so i changed the code  to:

`-$html = str_replace('jQuery(.+)\.tooltip\(.+\)\;', '', $app->getBody());`
`+$html = preg_replace("/jQuery(.+)\.tooltip\(.+\)\;/i", "<!-- Removed tooltip -->", $app->getBody());`

And removes the need for the $toreplace.

**Comment by Didldu-Florian** [comment]
Hi @jareis great, thanks for that fix.
It would be great, if you can open a pull request ;)
